### ISSUE TITLE
could this work with WebReflection/import.js ?

### ISSUE THREAD

**Issue by thisconnect** [rollup/rollup-starter-code-splitting#1]
hi

great example thanks!

As nomodule fallback this is building for system. But I wonder if we could use
https://github.com/WebReflection/import.js instead of systemjs?

and build iife or umd as nomodule fallback, but in my test iife or umd does currently not support experimentalCodeSplitting

**Comment by guybedford** [comment]
That project may well work with the direct `es` module output, but it would need to be tested and I'm not sure what the performance implications might be.

SystemJS is designed as a fallback for older browsers as a module loader is required to be able to dynamically load chunks. There's no way to make that work through iife, but an AMD loader can definitely be used with the AMD output so SystemJS is by no means the only option.

**Comment by thisconnect** [comment]
@guybedford makes sense thanks
