### ISSUE TITLE
Broken in Edge

### ISSUE THREAD

**Issue by kaheglar** [rollup/rollup-starter-code-splitting#11]
Beacuse `window.supportsDynamicImport` is evaluating true.

_* Tested in Edge 16, can't comment on other versions._

**Comment by kaheglar** [comment]
Apologies for the delay.

Added console logs as follows:

```
<script>
	import("/module/main-a.js");
	import("/module/main-b.js");
	window.supportsDynamicImport = true;

	console.log('<script> 1 supportsDynamicImport=', window.supportsDynamicImport);
</script>
<script>
	if (!window.supportsDynamicImport) {
		const systemJsLoaderTag = document.createElement('script');
		systemJsLoaderTag.src = 'https://unpkg.com/systemjs@2.0.0-alpha.1/dist/s.min.js';
		systemJsLoaderTag.addEventListener('load', function () {
			System.import('./nomodule/main-a.js');
			System.import('./nomodule/main-b.js');
		});
		document.head.appendChild(systemJsLoaderTag);
			
		console.log('<script> 2.1 supportsDynamicImport=', window.supportsDynamicImport);
	}
		
	console.log('<script> 2 supportsDynamicImport=', window.supportsDynamicImport);
</script>
```

![edge](https://user-images.githubusercontent.com/329747/49042420-0f72d980-f1c0-11e8-8288-28713ad5e2cb.png)

**Comment by kaheglar** [comment]
@guybedford

![edge](https://user-images.githubusercontent.com/329747/49049101-7b137180-f1d5-11e8-9d41-181404d21bcc.png)

**Comment by guybedford** [comment]
@kaheglar yes but inline in the script there, as you can see a syntax error or execution error will stop the `window.supportsDynamicImport = true` line from running, which is apparently not happening.

**Comment by guybedford** [comment]
So - 

```html
<script>
	console.log(import("/module/main-a.js"));
	console.log(import("/module/main-b.js"));
	window.supportsDynamicImport = true;

	console.log('<script> 1 supportsDynamicImport=', window.supportsDynamicImport);
</script>
```

**Comment by kaheglar** [comment]
Yes it's pretty odd behavior. I'm happy to close this if it's something you don't want to address?

**Comment by guybedford** [comment]
I'm happy to address it, I'm just asking for a clear log of the last code I commented.

**Comment by kaheglar** [comment]
Look at the screenshot again:
```js
import("/module/main-a.js")
```
return a Promise (No error, that's weird)

```js
import()
```
throws Syntax Error

**Comment by guybedford** [comment]
Ah I see... modules don’t necessarily run the same in the console, but the
promise from the dynamic import is interesting. My guess is the promise is
rejecting.. if you add a catch and then handler it should be possible to
verify this.

If so then for this specific version of edge we may need to modify the
detection to handle the promise.

**Comment by guybedford** [comment]
Given that Edge simply breaks the feature detection here, I'm not sure there is a fix apart from user agent sniffing.

@kaheglar I'd recommend replacing `window.supportsDynamicImport = true` with:

```js
window.supportsDynamicImport = navigator.userAgent.substr(navigator.userAgent.lastIndexOf('.') - 7, 7) !== 'Edge/16';
``

**Comment by kaheglar** [comment]
Yep that's a reasonable solution, thanks
