### ISSUE TITLE
Documenting dynamic import feature detection

### ISSUE THREAD

**Issue by guybedford** [rollup/rollup-starter-code-splitting#4]
Firefox supports skipping nomodule, but not dynamic import.

To handle this case, I've created a simple approach at https://github.com/rollup/rollup/issues/2285#issuecomment-398501242.

The hard part is working out how to document this case with the least possible confusion for users. Blog post!?

**Comment by guybedford** [comment]
Created https://github.com/rollup/rollup-starter-code-splitting/pull/5.

**Comment by camille-hdl** [comment]
for what it's worth, I wrote a few lines [here](https://medium.com/@eartz_hc/dynamic-import-of-es6-modules-with-fallback-to-systemjs-c72b30b8225e) about the solution you gave me.

**Comment by guybedford** [comment]
Nice. I guess we can close this now as well.
